services:
  db:
    image: postgres:15
    container_name: windsurf-db
    environment:
      POSTGRES_DB: windsurf
      POSTGRES_USER: windsurfuser
      POSTGRES_PASSWORD: windsurfpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: windsurf-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
